// Monster system data for server (CommonJS)

// Monster templates
const MONSTER_TEMPLATES = {
    'slime': {
        name: 'Slime Xanh',
        level: 1,
        maxHp: 100,
        attack: 10,
        defense: 2,
        goldDrop: 5,
        expDrop: 10,
        attackRange: 60,
        aggroRange: 100,
        sprite: '/assets/monster/monster.gif',
    },
    'rat': {
        name: 'Chuột Hoang',
        level: 1,
        maxHp: 80,
        attack: 8,
        defense: 1,
        goldDrop: 3,
        expDrop: 8,
        attackRange: 50,
        aggroRange: 90,
        sprite: '/assets/monster/monster.gif',
    },
    'bat': {
        name: 'Dơi Ma',
        level: 2,
        maxHp: 120,
        attack: 15,
        defense: 3,
        goldDrop: 8,
        expDrop: 15,
        attackRange: 65,
        aggroRange: 110,
        sprite: '/assets/monster/monster.gif',
    },
    'goblin': {
        name: 'Goblin',
        level: 3,
        maxHp: 200,
        attack: 25,
        defense: 5,
        goldDrop: 15,
        expDrop: 30,
        attackRange: 80,
        aggroRange: 120,
        sprite: '/assets/monster/monster.gif',
    },
    'wolf': {
        name: 'Sói Rừng',
        level: 4,
        maxHp: 250,
        attack: 35,
        defense: 8,
        goldDrop: 20,
        expDrop: 40,
        attackRange: 70,
        aggroRange: 130,
        sprite: '/assets/monster/monster.gif',
    },
    'orc': {
        name: 'Orc Chiến Binh',
        level: 5,
        maxHp: 350,
        attack: 40,
        defense: 10,
        goldDrop: 30,
        expDrop: 50,
        attackRange: 90,
        aggroRange: 140,
        sprite: '/assets/monster/monster.gif',
    },
    'skeleton': {
        name: 'Bộ Xương',
        level: 6,
        maxHp: 400,
        attack: 50,
        defense: 12,
        goldDrop: 40,
        expDrop: 60,
        attackRange: 85,
        aggroRange: 135,
        sprite: '/assets/monster/monster.gif',
    },
    'troll': {
        name: 'Troll Đá',
        level: 7,
        maxHp: 500,
        attack: 60,
        defense: 15,
        goldDrop: 50,
        expDrop: 80,
        attackRange: 95,
        aggroRange: 140,
        sprite: '/assets/monster/monster.gif',
    },
    'demon': {
        name: 'Ác Quỷ',
        level: 8,
        maxHp: 600,
        attack: 75,
        defense: 18,
        goldDrop: 70,
        expDrop: 100,
        attackRange: 100,
        aggroRange: 150,
        sprite: '/assets/monster/monster.gif',
    },
    'dragon': {
        name: 'Rồng Nhỏ',
        level: 10,
        maxHp: 800,
        attack: 100,
        defense: 25,
        goldDrop: 100,
        expDrop: 150,
        attackRange: 120,
        aggroRange: 160,
        sprite: '/assets/monster/monster.gif',
    },
    'boss-dragon': {
        name: 'Rồng Lửa',
        level: 15,
        maxHp: 1500,
        attack: 150,
        defense: 35,
        goldDrop: 200,
        expDrop: 300,
        attackRange: 140,
        aggroRange: 180,
        sprite: '/assets/monster/monster.gif',
    },
};

// Monster spawns per map
const MAP_MONSTERS = {
    'map1': [], // Làng Tân Thủ - an toàn, không có monsters
    'map2': [ // Rừng Hắc Ám - monsters trung bình
        { ...MONSTER_TEMPLATES['slime'], monsterId: 'map2-slime-1', x: 300, y: 400 },
        { ...MONSTER_TEMPLATES['slime'], monsterId: 'map2-slime-2', x: 500, y: 600 },
        { ...MONSTER_TEMPLATES['bat'], monsterId: 'map2-bat-1', x: 400, y: 300 },
        { ...MONSTER_TEMPLATES['bat'], monsterId: 'map2-bat-2', x: 900, y: 500 },
        { ...MONSTER_TEMPLATES['goblin'], monsterId: 'map2-goblin-1', x: 800, y: 300 },
        { ...MONSTER_TEMPLATES['goblin'], monsterId: 'map2-goblin-2', x: 1100, y: 800 },
        { ...MONSTER_TEMPLATES['wolf'], monsterId: 'map2-wolf-1', x: 1000, y: 700 },
        { ...MONSTER_TEMPLATES['wolf'], monsterId: 'map2-wolf-2', x: 600, y: 800 },
    ],
    'map3': [], // Thành Chủ - an toàn, không có monsters
    'map4': [ // Đồng Cỏ - monsters đa dạng
        { ...MONSTER_TEMPLATES['slime'], monsterId: 'map4-slime-1', x: 400, y: 500 },
        { ...MONSTER_TEMPLATES['slime'], monsterId: 'map4-slime-2', x: 1200, y: 400 },
        { ...MONSTER_TEMPLATES['goblin'], monsterId: 'map4-goblin-1', x: 900, y: 400 },
        { ...MONSTER_TEMPLATES['goblin'], monsterId: 'map4-goblin-2', x: 1400, y: 900 },
        { ...MONSTER_TEMPLATES['wolf'], monsterId: 'map4-wolf-1', x: 600, y: 900 },
        { ...MONSTER_TEMPLATES['wolf'], monsterId: 'map4-wolf-2', x: 300, y: 700 },
        { ...MONSTER_TEMPLATES['orc'], monsterId: 'map4-orc-1', x: 1200, y: 800 },
        { ...MONSTER_TEMPLATES['orc'], monsterId: 'map4-orc-2', x: 500, y: 300 },
        { ...MONSTER_TEMPLATES['troll'], monsterId: 'map4-troll-1', x: 1000, y: 1000 },
    ],
    'map5': [ // Hang Động - monsters mạnh và boss
        { ...MONSTER_TEMPLATES['orc'], monsterId: 'map5-orc-1', x: 400, y: 400 },
        { ...MONSTER_TEMPLATES['orc'], monsterId: 'map5-orc-2', x: 900, y: 700 },
        { ...MONSTER_TEMPLATES['skeleton'], monsterId: 'map5-skeleton-1', x: 700, y: 600 },
        { ...MONSTER_TEMPLATES['skeleton'], monsterId: 'map5-skeleton-2', x: 900, y: 300 },
        { ...MONSTER_TEMPLATES['skeleton'], monsterId: 'map5-skeleton-3', x: 300, y: 700 },
        { ...MONSTER_TEMPLATES['troll'], monsterId: 'map5-troll-1', x: 500, y: 500 },
        { ...MONSTER_TEMPLATES['demon'], monsterId: 'map5-demon-1', x: 800, y: 400 },
        { ...MONSTER_TEMPLATES['demon'], monsterId: 'map5-demon-2', x: 400, y: 800 },
        { ...MONSTER_TEMPLATES['dragon'], monsterId: 'map5-dragon-1', x: 600, y: 700 },
        { ...MONSTER_TEMPLATES['boss-dragon'], monsterId: 'map5-boss-1', x: 600, y: 450 }, // Boss chính
    ],
};

module.exports = {
    MONSTER_TEMPLATES,
    MAP_MONSTERS
};
